Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -152,17 +152,17 @@ jobs:
         if: ${{ always() && steps.build_with_security.conclusion }}
         id: build_with_security_exit_code
         run: |
-          if [ -f gradle-exit-code-${{ matrix.jdk-version }}-false.txt ]; then
-            error_output=$(cat gradle-error-${{ matrix.jdk-version }}-false.log 2>/dev/null | tr '\n' ' ' | tr -d '\r' || echo "No error output captured.")
-            echo "error_output_false=$error_output" >> $GITHUB_ENV
-            exit_code=$(cat gradle-exit-code-${{ matrix.jdk-version }}-false.txt)
+          if [ -f gradle-exit-code-${{ matrix.jdk-version }}-true.txt ]; then
+            error_output=$(cat gradle-error-${{ matrix.jdk-version }}-true.log 2>/dev/null | tr '\n' ' ' | tr -d '\r' || echo "No error output captured.")
+            echo "error_output_true=$error_output" >> $GITHUB_ENV
+            exit_code=$(cat gradle-exit-code-${{ matrix.jdk-version }}-true.txt)
             exit ${exit_code:-1}
           fi
 
       - name: failure
         if: ${{ always() && steps.build_with_security_exit_code.conclusion == 'failure' }}
         run: |
-          if echo "${{ env.error_output_false }}" | grep -q 'dependency-verification-report.html'; then
+          if echo "${{ env.error_output_true }}" | grep -q 'dependency-verification-report.html'; then
             echo "write_comment_with_security=true"
             echo "write_comment_with_security=true" >> $GITHUB_ENV
           else
