Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -53,37 +53,104 @@ jobs:
 
       - name: Check Gradle Build Exit Code (no spring security)
         if: ${{ always() && steps.build_without_security.conclusion }}
+        id: build_without_security_exit_code
         run: |
-          cat gradle-error-${{ matrix.jdk-version }}-false.log
           if [ -f gradle-exit-code-${{ matrix.jdk-version }}-false.txt ]; then
-            error_output=$(cat gradle-error-${{ matrix.jdk-version }}-false.log 2>/dev/null | tr '\n' ' ' | tr -d '\r' || echo "No error output captured.")
-            if echo $error_output | grep -q 'dependency-verification-report.html'; then
-              echo "schreib einen Kommentar"
-            fi
+            cat gradle-error-${{ matrix.jdk-version }}-false.log
             exit_code=$(cat gradle-exit-code-${{ matrix.jdk-version }}-false.txt)
-            echo "The Gradle build failed with exit code $exit_code"
-            echo "exit_code_false=$exit_code" >> $GITHUB_ENV
-            echo "error_output_false=$error_output" >> $GITHUB_ENV
-          else
-            echo "exit_code_false=0" >> $GITHUB_ENV
-            echo "error_output_false=" >> $GITHUB_ENV
+            exit ${exit_code:-1}
           fi
-
-      # - name: Failure Handling (no spring security)
-      #   # if: ${{ env.exit_code_false != '0' }}
-      #   run: |
-      #     echo "The Gradle build step failed with exit code ${{ env.exit_code_false }}"
-      #     if echo "${{ env.error_output_false }}"; then
-      #       exit_code=${{ env.exit_code_false }}
-      #       exit ${exit_code:-1}
-      #     fi
+          # cat gradle-error-${{ matrix.jdk-version }}-false.log
+          # if [ -f gradle-exit-code-${{ matrix.jdk-version }}-false.txt ]; then
+          #   error_output=$(cat gradle-error-${{ matrix.jdk-version }}-false.log 2>/dev/null | tr '\n' ' ' | tr -d '\r' || echo "No error output captured.")
+          #   if echo $error_output | grep -q 'dependency-verification-report.html'; then
+          #     echo "schreib einen Kommentar"
+          #   fi
+          #   exit_code=$(cat gradle-exit-code-${{ matrix.jdk-version }}-false.txt)
+          #   echo "The Gradle build failed with exit code $exit_code"
+          #   echo "exit_code_false=$exit_code" >> $GITHUB_ENV
+          #   echo "error_output_false=$error_output" >> $GITHUB_ENV
+          # else
+          #   echo "exit_code_false=0" >> $GITHUB_ENV
+          #   echo "error_output_false=" >> $GITHUB_ENV
+          # fi
 
       - name: failure
-        if: ${{ always() && steps.build_without_security.conclusion }}
+        if: ${{ always() && steps.build_without_security_exit_code.conclusion == "failure" }}
         run: |
           if echo "${{ env.error_output_false }}" | grep -q 'dependency-verification-report.html'; then
-            echo ${{ steps.build_without_security.conclusion }}
+            echo "write_comment=true" >> $GITHUB_ENV
+          else
+            echo "write_comment=false" >> $GITHUB_ENV
           fi
+      - name: PR | Post comment
+        if: ${{ always() && github.event_name == 'pull_request' && steps.build_without_security_exit_code.conclusion == "failure" && env.write_comment == "true" }}
+        run: |
+          echo ${{ steps.build_without_security_exit_code.conclusion }}
+      #   uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
+      #   with:
+      #     script: |
+      #       const { GITHUB_REPOSITORY, SCRIPT_OUTPUT } = process.env;
+      #       const [repoOwner, repoName] = GITHUB_REPOSITORY.split('/');
+      #       const prNumber = context.issue.number;
+
+      #       // Find existing comment
+      #       const comments = await github.rest.issues.listComments({
+      #         owner: repoOwner,
+      #         repo: repoName,
+      #         issue_number: prNumber
+      #       });
+
+      #       const comment = comments.data.find(c => c.body.includes("🚨 **Gradle Build Failed** 🚨"));
+
+      #       if (!comment) {
+      #         // Create new comment if no existing comment is found
+      #         await github.rest.issues.createComment({
+      #           owner: repoOwner,
+      #           repo: repoName,
+      #           issue_number: prNumber,
+      #           body: `🚨 **Gradle Build Failed** 🚨
+
+      #           Check: https://github.com/Stirling-Tools/Stirling-PDF/blob/main/DeveloperGuide.md#managing-dependencies
+      #           `
+      #         });
+      #         console.log("Created new comment.");
+      #       } else {
+      #         console.log("Comment update attempt denied. Actor does not match.");
+      #       }
+
+      # - name: PR | Delete comment
+      #   if: env.FAIL_JOB == 'false' && github.event_name == 'pull_request'
+      #   uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
+      #   with:
+      #     script: |
+      #       const { GITHUB_REPOSITORY, SCRIPT_OUTPUT } = process.env;
+      #       const [repoOwner, repoName] = GITHUB_REPOSITORY.split('/');
+      #       const prNumber = context.issue.number;
+
+      #       // Find existing comment
+      #       const comments = await github.rest.issues.listComments({
+      #         owner: repoOwner,
+      #         repo: repoName,
+      #         issue_number: prNumber
+      #       });
+
+      #       const comment = comments.data.find(c => c.body.includes("🚨 **Gradle Build Failed** 🚨"));
+
+      #       // Only allow the action user to update comments
+      #       const expectedActor = "github-actions[bot]";
+
+      #       if (comment && comment.user.login === expectedActor) {
+      #         // deleted existing comment
+      #         await github.rest.issues.deleteComment({
+      #           owner: repoOwner,
+      #           repo: repoName,
+      #           comment_id: comment.id
+      #         });
+      #         console.log("Deleted existing comment.");
+      #       } else {
+      #         console.log("Comment deleted attempt denied. Actor does not match.");
+      #       }
 
       - name: Build with Gradle and with spring security
         id: build_with_security
@@ -110,15 +177,6 @@ jobs:
             echo "error_output_true=" >> $GITHUB_ENV
           fi
 
-      # - name: Failure Handling
-      #   if: ${{ env.exit_code_true != '0' }}
-      #   run: |
-      #     echo "The Gradle build step failed with exit code ${{ env.exit_code_true }}"
-      #     if echo "${{ env.error_output_true }}"; then
-      #       exit_code=${{ env.exit_code_true }}
-      #       exit ${exit_code:-1}
-      #     fi
-
       - name: failure
         if: ${{ always() && steps.build_with_security.conclusion }}
         run: |
@@ -134,8 +192,6 @@ jobs:
           path: |
             gradle-error-${{ matrix.jdk-version }}-true.log
             gradle-error-${{ matrix.jdk-version }}-false.log
-            gradle-exit-code-${{ matrix.jdk-version }}-true.txt
-            gradle-exit-code-${{ matrix.jdk-version }}-false.txt
             build/reports/tests/
             build/test-results/
             build/reports/problems/
