Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -30,19 +30,6 @@ jobs:
         with:
           egress-policy: audit
 
-      - name: Generate GitHub App Token
-        id: generate-token
-        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
-        with:
-          app-id: ${{ vars.GH_APP_ID }}
-          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
-
-      - name: Get GitHub App User ID
-        id: get-user-id
-        run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
-        env:
-          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
-
       - name: Checkout repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
@@ -52,28 +39,23 @@ jobs:
           java-version: ${{ matrix.jdk-version }}
           distribution: "temurin"
 
-      - run: |
+      - if: github.event.pull_request.user.login == 'dependabot[bot]'
+        run: |
           # Generate verification metadata with signatures and checksums
-          ./gradlew --write-verification-metadata sha256 --refresh-dependencies help
-          ./gradlew --write-verification-metadata pgp,sha256 --refresh-keys --export-keys --refresh-dependencies help
+          ./gradlew clean dependencies buildEnvironment spotlessApply --write-verification-metadata sha256 --refresh-dependencies help
+          ./gradlew clean dependencies buildEnvironment spotlessApply --write-verification-metadata pgp,sha256 --refresh-keys --export-keys --refresh-dependencies help
 
-      - run: |
-          git config --global user.name "AstraGermany-Bot"
-          git config --global user.email "195330822+astragermany-bot[bot]@users.noreply.github.com"
-          git add gradle/verification-metadata.xml
-          git add gradle/verification-keyring.keys
-          git commit -m "Update verification files"
-          git push origin HEAD:${{ github.ref_name }}
-        env:
-          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
+      - if: github.event.pull_request.user.login != 'dependabot[bot]'
+        run: |
+
 
       - name: Build with Gradle and no spring security
-        run: ./gradlew clean build
+        run: ./gradlew clean build || echo "FAIL_JOB=true" >> $GITHUB_ENV
         env:
           DOCKER_ENABLE_SECURITY: false
 
       - name: Build with Gradle and with spring security
-        run: ./gradlew clean build
+        run: ./gradlew clean build || echo "FAIL_JOB=true" >> $GITHUB_ENV
         env:
           DOCKER_ENABLE_SECURITY: true
 
